apiVersion: v1
kind: Service
metadata:
  name: iot-station-management-postgres-service
  namespace: smart-city-traffic
spec:
  selector:
    app: iot-station-management-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
