apiVersion: v1
kind: Service
metadata:
  name: iot-station-management-mongo-service
  namespace: smart-city-traffic
spec:
  selector:
    app: iot-station-management-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
